### PR TITLE
Main+goal reached

### PR DESCRIPTION
**Pull request by vincentstocks**
small "bug" where on app start the dashboard shows a goal reached card instead of current goal card, until the current stepcount is loaded in through stepsviewmodel. might not even be visible on actual phone, but my emulator is slow

### CODE REVIEW

**Review by Piixiiee — COMMENTED** [review]
Fint!

**Comment by Piixiiee** [comment]
Fint!

**Review by Piixiiee — APPROVED** [review]

**Review by lutches — COMMENTED** [review]
functionalitet I main e lite sus. men det funkar la

**Review by Dunkaburk — COMMENTED** [review]
Nice bro

**Pull request merged**
